#!/bin/bash

set -e

#Allow instruqt time to do it's thing
sleep 10

# script to fetch / update assets from VCS
cat <<-EOF > /bin/get_assets
#!/bin/bash
echo "cloning assets..."
cd /root
git clone https://github.com/egarelnabi/hackathon2020

cp -r hackathon2020/app_k8s .
cp -r hackathon/app_terraform .
rm -rf hackathon2020
EOF
chmod +x /bin/get_assets
get_assets


# deploy app to EKS
kubectl config use-context eks_frontend
kubectl apply -f app_k8s --namespace=consul
sleep 10


# expose app services public IPs
kubectl expose deployment frontend --type=LoadBalancer --name=my-frontend
#kubectl expose deployment products-api --type=LoadBalancer --name=my-products-api
#kubectl expose deployment public-api --type=LoadBalancer --name=my-public-api
#kubectl expose deployment postgres --type=LoadBalancer --name=my-postgres

 


#setup Vault app credentials
vault secrets enable kv
#vault secrets enable -path="kv" kv
vault kv put kv/db/postgres/product-db-creds username=postgres password=password
#put in permissions here
kubectl rollout restart deployment products-api-deployment



 


exit 0
